# action.yml
name: 'Make python'
description: 'make, make docs, make test and publish python code'
inputs:
  publish:
    default: false
  test:
    default: true
  doc:
    default: false

runs:
  using: "composite"
  steps:
    - name: work around permission issue
      run: git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
    - uses: actions/checkout@v3
      with:
        fetch-depth: "0"
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - run: make build
    - run: make install
    - run: make test
      if: ${{ inputs.test }}
    - name: Build Sphinx
      if: ${{ inputs.doc }}
      run: rm -rf build && make clean-all && make html