# action.yml
name: 'Make python'
description: 'make, make docs, make test and publish python code'
inputs:
  build:
    default: true
  install:
    default: true
  test:
    default: true
  doc:
    default: false
  gh-pages:
    default: false
  coveralls:
    default: false
  test-gh-pages:
    default: false
  pypi-token:
    required: false
  test-pypi-token:
    required: false
  codacy-api-token:
    required: false
  coverage-reports:
    default: coverage.xml

runs:
  using: "composite"
  steps:
    - name: work around permission issue
      run: git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
      shell: bash
    - uses: actions/checkout@v3
      with:
        fetch-depth: "0"
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      shell: bash

    - run: make build
      shell: bash
      if: ${{ inputs.build == 'true' }}
    - run: make install
      shell: bash
      if: ${{ inputs.install == 'true' }}
    - run: make test
      shell: bash
      if: ${{ inputs.test == 'true' }}
    - name: Build Sphinx
      shell: bash
      if: ${{ inputs.doc == 'true' }}
      run: rm -rf build && make clean-all && make html  
    - name: Report Coveralls
      if: ${{ inputs.coveralls == 'true' }}
      uses: AndreMiras/coveralls-python-action@develop
    - name: Report Codacy
      if: "${{ inputs.codacy-api-token != '' }}"
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ inputs.codacy-api-token }}
        # or
        #api-token: ${{ secrets.CODACY_API_TOKEN }}
        coverage-reports: ${{ inputs.coverage-reports }}
    - name: Deploy Test PyPI
      if: "${{ inputs.test-pypi-token != '' }}"
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ inputs.test-pypi-token }}
        repository_url: https://test.pypi.org/legacy/
    - name: Deploy PyPI
      if: "${{ inputs.pypi-token != '' }}"
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ inputs.pypi-token }}
    - name: Upload Test Github Pages
      if: ${{ inputs.test-gh-pages == 'true' }}
      uses: JamesIves/github-pages-deploy-action@v4.4.0
      with:
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: build/html # The folder the action should deploy.
        target-folder: test
    - name: Deploy Github Pages
      if: ${{ inputs.gh-pages == 'true' }}
      uses: JamesIves/github-pages-deploy-action@v4.4.0
      with:
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: build/html # The folder the action should deploy.
        clean-exclude: test/
