# action.yml
name: 'Make python'
branding:
  icon: 'code'
  color: 'blue'
description: 'make, make docs, make test and publish python code'
inputs:
  ci:
    default: false
  build:
    default: true
  install:
    default: true

  python-version:
    default: ''
  test:
    default: true
    
  doc:
    default: false
  gh-pages:
    default: false
  test-gh-pages:
    default: false
  gh-pages-branch:
    default: gh-pages
  gh-pages-folder:
    default: docs/build/html
  pypi-token:
    required: false
  test-pypi-token:
    required: false
    
  coveralls:
    default: false
  codacy-api-token:
    required: false
  coverage-reports:
    default: coverage.xml

runs:
  using: "composite"
  steps:
    - name: work around permission issue
      run: git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
      shell: bash
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
      if: ${{ inputs.ci != '' }}
    - run: make ci
      shell: bash
      if: ${{ inputs.ci == 'true' }}
    - run: make build
      shell: bash
      if: ${{ inputs.build == 'true' }}
    - run: make install
      shell: bash
      if: ${{ inputs.install == 'true' }}
    - run: make test
      shell: bash
      if: ${{ inputs.test == 'true' }}
    - run: make doc  
      shell: bash
      if: ${{ inputs.doc == 'true' }}
    - name: Report Coveralls
      if: ${{ inputs.coveralls == 'true' }}
      uses: AndreMiras/coveralls-python-action@develop
    - name: Report Codacy
      if: "${{ inputs.codacy-api-token != '' }}"
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ inputs.codacy-api-token }}
        # or
        #api-token: ${{ secrets.CODACY_API_TOKEN }}
        coverage-reports: ${{ inputs.coverage-reports }}
    - name: Deploy Test PyPI
      if: "${{ inputs.test-pypi-token != '' }}"
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ inputs.test-pypi-token }}
        repository_url: https://test.pypi.org/legacy/
    - name: Deploy PyPI
      if: "${{ inputs.pypi-token != '' }}"
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ inputs.pypi-token }}
    - name: Upload Test Github Pages
      if: ${{ inputs.test-gh-pages == 'true' }}
      uses: JamesIves/github-pages-deploy-action@v4.7.2
      with:
        BRANCH: ${{ inputs.gh-pages-branch }}  # The branch the action should deploy to.
        FOLDER: ${{ inputs.gh-pages-folder }}  # The folder the action should deploy.
        target-folder: test
    - name: Deploy Github Pages
      if: ${{ inputs.gh-pages == 'true' }}
      uses: JamesIves/github-pages-deploy-action@v4.7.2
      with:
        BRANCH: ${{ inputs.gh-pages-branch }} # The branch the action should deploy to.
        FOLDER: ${{ inputs.gh-pages-folder }}  # The folder the action should deploy.
        clean-exclude: test/
